Sprint 14. Part 2
Vagner-Viktor/java-shareit pull request #2
Opened 2024-07-15 21:24 UTC by Vagner-Viktor

Доработано в соотвествии с ТЗ 15

2024-07-16 15:19 UTC, ErkinKasymaliev requested changes
привет, оставил коммент.
Также, если в каком то entity используете @ManyToOne, то не забывайте в противоположном entity использовать @OneToMany

2024-07-16 15:19 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (bookingRequestDto.getEnd() == null) {
```
 if (bookingRequestDto.getEnd() == null) {
            throw new ValidationException("End date is null!");
        }
        if (bookingRequestDto.getStart() == null) {
            throw new ValidationException("Start date is null!");
        }
        if (bookingRequestDto.getEnd().isBefore(LocalDateTime.now())) {
            throw new ValidationException("End date before now!");
        }
        if (bookingRequestDto.getStart().isBefore(LocalDateTime.now())) {
            throw new ValidationException("Start date before now!");
        }
        if (bookingRequestDto.getEnd().isBefore(bookingRequestDto.getStart())) {
            throw new ValidationException("End date before Start date!");
        }
        if (bookingRequestDto.getEnd().equals(bookingRequestDto.getStart())) {
            throw new ValidationException("End date equals Start date!");
        }
```

эти проверки уберите в начало метода, чтоб лишний раз бд не вызывать

2024-07-16 15:19 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return BookingMapper.toBookingDto(bookingRepository.save(
ух блин, ну функциональщина) ну ок, вроде читаемо

2024-07-16 15:19 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private String status;
верните enum и используйте @Enumerated

2024-07-16 15:19 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/comment/dao/CommentRepository.java
> +
лишние строки

2024-07-16 15:19 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        HashMap<Long, Item> items = new HashMap<>();
вот это вот все: 3 запроса в бд и маппинг  3х массивов удаляем!
в Item.java добавляем поля: 
```
@OneToMany
private List<Booking> bookings;
@OneToMany
private List<Comment> comments;

itemRepository.findAllByOwnerIdOrderByIdAsc(userId).stream()
                .map(маппите в ItemInfoDto)
```

2024-07-16 15:19 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +//        if (!userRepository.isUserExist(userId)) {
не оставляйте закоменченный код

2024-07-16 15:19 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        // if (userRepository.isUserByEmailExist(userDto.getEmail())) {
тоже самое

2024-07-17 19:53 UTC, Vagner-Viktor commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +@AllArgsConstructor
исправил

2024-07-17 19:54 UTC, Vagner-Viktor commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (bookingRequestDto.getEnd() == null) {
исправил

2024-07-17 19:58 UTC, Vagner-Viktor commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private String status;
исправил

2024-07-17 19:58 UTC, Vagner-Viktor commented on src/main/java/ru/practicum/shareit/comment/dao/CommentRepository.java
> +
убрал

2024-07-17 19:58 UTC, Vagner-Viktor commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        HashMap<Long, Item> items = new HashMap<>();
исправил

2024-07-17 19:58 UTC, Vagner-Viktor commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +//        if (!userRepository.isUserExist(userId)) {
убрал

2024-07-17 19:58 UTC, Vagner-Viktor commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        // if (userRepository.isUserByEmailExist(userDto.getEmail())) {
убрал

2024-07-18 11:51 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-07-18 13:26 UTC, merged