Sprint 16. ShareIt. Part 3
Vagner-Viktor/java-shareit pull request #3
Opened 2024-07-29 19:54 UTC by Vagner-Viktor

Add item requests and gateway

2024-07-30 05:19 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-07-30 05:19 UTC, ErkinKasymaliev commented on server/pom.xml
> +        <dependency>
это отсюда убираем, и всю валидацию из server

2024-07-30 05:19 UTC, ErkinKasymaliev commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> -            throw new NotFoundException("User id = " + userId + " not found!");
так должно же быть NotFound

2024-07-30 05:19 UTC, ErkinKasymaliev commented on server/src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @NotNull
убираем

2024-07-30 05:19 UTC, ErkinKasymaliev commented on server/src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @NotNull
убираем

2024-07-30 05:19 UTC, ErkinKasymaliev commented on server/src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @NotNull
убираем

2024-07-30 05:19 UTC, ErkinKasymaliev commented on server/src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>      @NotNull
убираем

2024-07-30 13:04 UTC, Vagner-Viktor commented on server/src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> -            throw new NotFoundException("User id = " + userId + " not found!");
да, должно быть NotFound, но добавили новые тесты Postman и там требуют другой ответ
<img width="921" alt="Screenshot 2024-07-30 at 15 02 59" src="https://github.com/user-attachments/assets/4dc7aee9-9cff-4a89-996b-17ca998f622c">

2024-07-30 13:05 UTC, Vagner-Viktor commented on server/pom.xml
> +        <dependency>
исправил

2024-07-30 13:06 UTC, Vagner-Viktor commented on server/src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @NotNull
готово

2024-07-30 13:06 UTC, Vagner-Viktor commented on server/src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @NotNull
готово

2024-07-30 13:06 UTC, Vagner-Viktor commented on server/src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @NotNull
готово

2024-07-30 13:06 UTC, Vagner-Viktor commented on server/src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>      @NotNull
готово

2024-07-31 09:00 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2024-07-31 09:18 UTC, merged